from ..template import Template

names_eng = Template(
    names=[
        'Nightsoul\'s Blessing',
        'Nightsoul point',
        'Nightsoul points',
        'Nightsoul Burst',
        'Nightsoul Bursts',

        'Elemental DMG Bonus',
        'Charged Attack DMG',
        'Elemental Burst DMG',
        'Elemental Skill DMG',
        'Normal Attack DMG',
        'Normal Attack SPD',
        'Plunging Attack DMG',
        'Lunar Reaction DMG',
        'Reaction DMG',
        'Elemental DMG',

        'Elemental Shard',
        'Elemental Skill',
        'Elemental Burst',
        'Elemental Bursts',
        'Elemental Reaction',
        'Elemental Skills',
        'Normal Attack',
        'Normal Attacks',
        'Charged Attack',
        'Charged Attacks',
        'Charge Attacks',
        'Plunging Attack',
        'Plunging Attacks',
        'Stamina cost',

        'Incoming Healing Bonus',
        'Healing Bonus',
        'Physical DMG Bonus',
        'Physical DMG',
        'Elemental RES',
        'Physical RES',
        'DMG Bonus',
        'Movement SPD',
        'Attack SPD',
        'ATK SPD',

        'Vaporize',
        'Melt',
        'Lunar Reactions',

        'Sword',
        'Claymore',
        'Polearm',
        'Catalyst',
        'Bow',
        'Normal',
        'Charged',

        'Elemental Mastery',
        'Shield Strength',
        'Energy Recharge',
        'Healing Effectiveness',
        'Healing Bonus',
        'Max HP',
        'CRIT Rate',
        'CRIT DMG',
        'Crit DMG',
        'HP',
        'Base ATK',
        'ATK',
        'DEF',
        'Elemental Energy',
        'Energy',
    ],
)

keywords_eng = Template(
    keywords=[
        ('Anemo DMG Bonus', 'anemo'),
        ('Cryo DMG Bonus', 'cryo'),
        ('Electro DMG Bonus', 'electro'),
        ('Geo DMG Bonus', 'geo'),
        ('Hydro DMG Bonus', 'hydro'),
        ('Pyro DMG Bonus', 'pyro'),
        ('Dendro DMG Bonus', 'dendro'),

        ('Anemo DMG', 'anemo'),
        ('Cryo DMG', 'cryo'),
        ('Electro DMG', 'electro'),
        ('Geo DMG', 'geo'),
        ('Hydro DMG', 'hydro'),
        ('Pyro DMG', 'pyro'),
        ('Dendro DMG', 'dendro'),

        ('Anemo RES', 'anemo'),
        ('Cryo RES', 'cryo'),
        ('Electro RES', 'electro'),
        ('Geo RES', 'geo'),
        ('Hydro RES', 'hydro'),
        ('Pyro RES', 'pyro'),
        ('Dendro RES', 'dendro'),

        ('Electro-Charged', 'electro'),
        ('Lunar-Charged', 'electro'),
        ('Crystallize Reaction', 'geo'),
        ('Electro Crystallize', 'electro'),
        ('Hydro Crystallize', 'hydro'),
        ('Cryo Crystallize', 'cryo'),
        ('Crystallize', 'geo'),
        ('Frozen', 'cryo'),
        ('Overloaded', 'pyro'),
        ('Burning', 'pyro'),
        ('Superconduct', 'cryo'),
        ('Electro Swirl', 'electro'),
        ('Hydro Swirl', 'hydro'),
        ('Cryo Swirl', 'cryo'),
        ('Swirl', 'anemo'),
        ('Quicken', 'dendro'),
        ('Burgeon', 'dendro'),
        ('Hyperbloom', 'dendro'),
        ('Lunar-Bloom', 'dendro'),
        ('Bloom', 'dendro'),
        ('Aggravate', 'electro'),
        ('Spread', 'dendro'),

        ('Dendro Cores', 'dendro'),
        ('Dendro Core', 'dendro'),

        ('Anemo', 'anemo'),
        ('Cryo', 'cryo'),
        ('Electro', 'electro'),
        ('Geo', 'geo'),
        ('Hydro', 'hydro'),
        ('Pyro', 'pyro'),
        ('Dendro', 'dendro'),
    ]
)

patterns_eng = Template(
    patterns=[
        (r'{M#(.*?)}', '\\1'),
        (r'{F#(.*?)}', ''),
        (r'{LAYOUT_PC#(.*?)}', '\\1'),
        (r'{LAYOUT_\w+#.*?}', ''),
        (r'{LINK\#N(\d+)}<color=\#\w+>(.*?)<\/color>{/LINK}', 'skill{n\\1:\\2}'),
        (r'{LINK\#N(\d+)}<color style=\'color\:\#\w+;\'>(.*?)<\/color>{/LINK}', 'skill{n\\1:\\2}'),
        (r'{LINK\#N(\d+)}(.*?){/LINK}', 'skill{n\\1:\\2}'),
        (r'{LINK\#\w+}(.*?){/LINK}', '\\1'),
        (r'<color=\#99FFFFFF>(.*?)<\/color>', 'cryo{\\1}'),
        (r'<color=\#FFE699FF>(.*?)<\/color>', 'geo{\\1}'),
        (r'<color=\#FF9999FF>(.*?)<\/color>', 'pyro{\\1}'),
        (r'<color=\#80C0FFFF>(.*?)<\/color>', 'hydro{\\1}'),
        (r'<color=\#FFACFFFF>(.*?)<\/color>', 'electro{\\1}'),
        (r'<color=\#80FFD7FF>(.*?)<\/color>', 'anemo{\\1}'),
        (r'<color=\#99FF88FF>(.*?)<\/color>', 'dendro{\\1}'),
        # (r'<color=\#FFD780FF>(.*?)<\/color>\\n', '<h2>\\1</h2>\\\\n'),
        (r'<color=\#FFD780FF>(.*?)<\/color>', 'name{\\1}'),

        (r"<color style='color\:\#99FFFF;'>(.*?)<\/color>", 'name{\\1}'),
        (r"<color style='color\:\#FFE699;'>(.*?)<\/color>", 'geo{\\1}'),
        (r"<color style='color\:\#FF9999;'>(.*?)<\/color>", 'pyro{\\1}'),
        (r"<color style='color\:\#80C0FF;'>(.*?)<\/color>", 'hydro{\\1}'),
        (r"<color style='color\:\#FFACFF;'>(.*?)<\/color>", 'electro{\\1}'),
        (r"<color style='color\:\#80FFD7;'>(.*?)<\/color>", 'anemo{\\1}'),
        (r"<color style='color\:\#99FF88;'>(.*?)<\/color>", 'dendro{\\1}'),
        (r"<color style='color\:\#FFD780;'>(.*?)<\/color>", 'name{\\1}'),

        # (r'</h2>(\\n)+', '</h2><p>'),
        (r'^([^<])', '<p>\\1'),
        (r'\\n\\n', '</p><p>'),
        (r'\\n', '<br>'),
        (r'(\\n)*$', '</p>'),
        (r'<p><h2>', '<h2>'),
        (r'<p>#', '<p>'),
    ]
)

color_patterns = Template(
    patterns=[
        (r'<color=\#99FFFFFF>(.*?)<\/color>', 'name{\\1}'),
        (r'<color=\#FFE699FF>(.*?)<\/color>', 'geo{\\1}'),
        (r'<color=\#FF9999FF>(.*?)<\/color>', 'pyro{\\1}'),
        (r'<color=\#80C0FFFF>(.*?)<\/color>', 'hydro{\\1}'),
        (r'<color=\#FFACFFFF>(.*?)<\/color>', 'electro{\\1}'),
        (r'<color=\#80FFD7FF>(.*?)<\/color>', 'anemo{\\1}'),
        (r'<color=\#99FF88FF>(.*?)<\/color>', 'dendro{\\1}'),
        (r'<color=\#FFD780FF>(.*?)<\/color>', 'name{\\1}'),

        (r"<color style='color\:\#99FFFF;'>(.*?)<\/color>", 'name{\\1}'),
        (r"<color style='color\:\#FFE699;'>(.*?)<\/color>", 'geo{\\1}'),
        (r"<color style='color\:\#FF9999;'>(.*?)<\/color>", 'pyro{\\1}'),
        (r"<color style='color\:\#80C0FF;'>(.*?)<\/color>", 'hydro{\\1}'),
        (r"<color style='color\:\#FFACFF;'>(.*?)<\/color>", 'electro{\\1}'),
        (r"<color style='color\:\#80FFD7;'>(.*?)<\/color>", 'anemo{\\1}'),
        (r"<color style='color\:\#99FF88;'>(.*?)<\/color>", 'dendro{\\1}'),
        (r"<color style='color\:\#FFD780;'>(.*?)<\/color>", 'name{\\1}'),
    ]
)

names_rus = Template(
    names=[
        'Вспышку Ночного духа',
        'Вспышке Ночного духа',
        'Благословение Ночного духа',
        'Благословения Ночного духа',
        'Ночного духа',

        'элементальный навык',
        'элементальных навыков',
        'элементального навыка',
        'элементальные навыки',
        'элементальным навыком',
        'элементальными навыками',
        'взрывом стихии',
        'взрыва стихии',
        'взрыва стихий',
        'элементальный осколок',
        'элементального урона',
        'элементальной реакции',
        'обычной атаки',
        'обычной атакой',
        'обычной атаке',
        'обычных атак',
        'обычную атаку',
        'Обычные атаки',
        'обычная атака',
        'обычными атаками',
        'заряженная атака',
        'заряженной атаки',
        'заряженной атакой',
        'заряженных атак',
        'заряженные атаки',
        'заряженными атаками',
        'атаками в падении',
        'атаки в падении',
        'атаку в падении',
        'атака в падении',
        'бонус физического урона',
        'атакой в падении',
        'атак в падении',

        'единиц энергии',
        'элементальной энергии',
        'Пар',
        'Таяние',
        'Лунные реакции',
        'Лунных реакций',
        'скорость передвижения',
        'скорость атаки',

        'одноручное',
        'двуручное',
        'древковое',
        'катализатор',
        'стрелковое',

        'шанс критического попадания',
        'Шанс крит. попадания',
        'критический урон',
        'крит. урон',
        'бонус получаемого лечения',

        'восстановления энергии',
        'восстановление энергии',
        'Мастерство стихий',
        'мастерство стихий',
        'мастерства стихий',
        'шанс крит. попадания',
        'Прочность щита',
        'прочность щита',
        'физ. урон',
        'сила атаки',
        'силу атаки',
        'силы атаки',
        'силе атаки',
        'эффективность лечения',
        'Бонус лечения',
        'бонус получаемого лечения',
        'получаемое лечение',
        'макс. HP',
        'макс. НР',
        'HP',
        'НР',
        'ед. энергии',
    ]
)

keywords_rus = Template(
    keywords=[
        ('Гео урона', 'geo'),
        ('Гео урону', 'geo'),
        ('Гео урон', 'geo'),
        ('Пиро урона', 'pyro'),
        ('Пиро урон', 'pyro'),
        ('Крио урона', 'cryo'),
        ('Крио урон', 'cryo'),
        ('Электро урона', 'electro'),
        ('Электро урон', 'electro'),
        ('Анемо урона', 'anemo'),
        ('Анемо урон', 'anemo'),
        ('Гидро урона', 'hydro'),
        ('Гидро урон', 'hydro'),
        ('Дендро урона', 'dendro'),
        ('Дендро урон', 'dendro'),

        ('Гидро сопротивление', 'hydro'),
        ('Дендро сопротивление', 'dendro'),
        ('Электро сопротивление', 'electro'),
        ('Крио сопротивление', 'cryo'),
        ('Гео сопротивление', 'geo'),
        ('Анемо сопротивление', 'anemo'),
        ('Пиро сопротивление', 'pyro'),

        ('Дендро ядра', 'dendro'),
        ('Дендро ядер', 'dendro'),

        ('Заряжен', 'electro'),
        ('Лунный заряд', 'electro'),
        ('Электро Кристалл', 'electro'),
        ('Гидро Кристалл', 'hydro'),
        ('Крио Кристалл', 'cryo'),
        ('Кристалл', 'geo'),
        ('Заморозка', 'cryo'),
        ('Перегрузка', 'pyro'),
        ('Горение', 'pyro'),
        ('Горения', 'pyro'),
        ('Сверхпроводник', 'cryo'),
        ('Крио Рассеивание', 'cryo'),
        ('Гидро Рассеивание', 'hydro'),
        ('Электро Рассеивание', 'electro'),
        ('Рассеивание', 'anemo'),
        ('Рассеивания', 'anemo'),
        ('Рассенивание', 'anemo'),
        ('Стимуляцию', 'dendro'),
        ('Стимуляция', 'dendro'),
        ('Лунная бутонизация', 'dendro'),
        ('Лунной бутонизации', 'dendro'),
        ('Бутонизацию', 'dendro'),
        ('Бутонизация', 'dendro'),
        ('Цветение', 'dendro'),
        ('Вегетация', 'dendro'),
        ('Вегетацию', 'dendro'),
        ('Обострение', 'electro'),
        ('Разрастание', 'dendro'),

        ('Гео', 'geo'),
        ('Пиро', 'pyro'),
        ('Крио', 'cryo'),
        ('Электро', 'electro'),
        ('Анемо', 'anemo'),
        ('Гидро', 'hydro'),
        ('Дендро', 'dendro'),

    ]
)
